version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI...
      - pip install awscli
  build:
    commands:
      - echo Deploying CloudFormation stack...
      - aws cloudformation deploy \
          --template-file s3-bucket.yml \
          --stack-name MyS3BucketStack \
          --parameter-overrides BucketName=my-cicd-bucket-demo-12345 \
          --capabilities CAPABILITY_NAMED_IAM
artifacts:
  files:
    - '**/*'
