AWSTemplateFormatVersion: "2010-09-09"
Description: Create or update an S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cicdbuckets3biva
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketNameOutput:
    Value: !Ref MyS3Bucket
    Description: The name of the created S3 bucket
